[build]
  base = "exampleSite"
  publish = "public"
  command = "hugo --gc --themesDir ../.. --theme repo"

[context.deploy-preview]
  command = "hugo --gc --buildFuture --themesDir ../.. --theme repo"

[context.branch-deploy]
  command = "hugo --gc --buildFuture --themesDir ../.. --theme repo"
